### ISSUE TITLE
dataSource or dataSourceClassName or jdbcUrl is required.

### ISSUE THREAD

**Issue by Elite-Programmer** [heroku/java-getting-started#128]
When setting up the sample app, this link http::localhost:5000/db returns the following error:
com.zaxxer.hikari.HikariConfig           : HikariPool-1 - dataSource or dataSourceClassName or jdbcUrl is required.

**Comment by Malax** [comment]
Hi there. Do you try to set this up locally or on Heroku?

**Comment by Elite-Programmer** [comment]
locally

**Comment by Elite-Programmer** [comment]
This works on Heroku. Marking this issue as resolved.

**Comment by Elite-Programmer** [comment]
It works on Heroku. You might close this issue. Thanks
