### ISSUE TITLE
Datasource not being recognized when running heroku local

### ISSUE THREAD

**Issue by ellenchristine** [heroku/java-getting-started#53]
From what I understand from the Heroku documentation, I should be able to access the database locally with no configuration updates to this project as long as I export the datasource (explained here: https://devcenter.heroku.com/articles/heroku-postgresql#local-setup), which I did.

However, I'm getting this error when trying to access localhost:5000/db.html in this project:

> dataSource or dataSourceClassName or jdbcUrl is required

Is there additional configuration required to get this to work locally? It works fine once it's deployed to Heroku remotely.

**Comment by mmautner** [comment]
After a little digging I've discovered that you should set a `JDBC_DATABASE_URL` environment variable which should look like this:

```
jdbc:postgresql://localhost:5432/my_database_name
```
[Source](https://stackoverflow.com/a/38235313)

Why `JDBC_DATABASE_URL` and not `DATABASE_URL` like all other typical Heroku apps? I'm not sure why that was chosen, but that's the environment variable name read from the Spring configuration file here:

https://github.com/heroku/java-getting-started/blob/master/src/main/resources/application.properties#L1

Setting that environment variable got things working for me:

![screen shot 2018-04-05 at 11 26 59 am](https://user-images.githubusercontent.com/1419652/38384538-4ac5842a-38c4-11e8-980f-3d511d5740e3.png)

**Comment by Malax** [comment]
I realize this is an old issue, but I want to shed some light on it before closing:

> Why JDBC_DATABASE_URL and not DATABASE_URL like all other typical Heroku apps?

JDBC requires a different URL schema. The Java buildpack will create JDBC_DATABASE_URL for you on Heroku based on DATABASE_URL. We do not override DATABASE_URL since the different schema could break other tools, addons, or apps.
