### ISSUE TITLE
Cant view the java web application after deploying

### ISSUE THREAD

**Issue by ShanChathusanda93** [heroku/java-getting-started#60]
Hi,

I deployed a java web app on heroku, but I cant access through the link that heroku provides. Logs said that the mvn build was success. When open the app using the cmd command and from the dashboard, it says that 

> Application error

> An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details.

My logs are clean as I know. Followings are my logs.

> 2018-04-29T16:03:39.435610+00:00 app[api]: Release v1 created by user shanchathusanda@gmail.com
> 2018-04-29T16:03:39.435610+00:00 app[api]: Initial release by user shanchathusanda@gmail.com
> 2018-04-29T16:03:40.427660+00:00 app[api]: Enable Logplex by user shanchathusanda@gmail.com
> 2018-04-29T16:03:40.427660+00:00 app[api]: Release v2 created by user shanchathusanda@gmail.com
> 2018-04-29T16:04:02.000000+00:00 app[api]: Build started by user shanchathusanda@gmail.com
> 2018-04-29T16:09:19.839596+00:00 app[api]: Deploy bfdb621d by user shanchathusanda@gmail.com
> 2018-04-29T16:09:19.839596+00:00 app[api]: Release v3 created by user shanchathusanda@gmail.com
> 2018-04-29T16:04:02.000000+00:00 app[api]: Build succeeded
> 2018-04-29T16:09:52.585394+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/" host=infinite-spire-46506.herokuapp.com request_id=313ff6e1-d1ab-4265-b540-39d10139894f fwd="112.134.44.149" dyno= connect= service= status=503 bytes= protocol=https
> 2018-04-29T16:09:53.914776+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/favicon.ico" host=infinite-spire-46506.herokuapp.com request_id=69ae9b29-cdcb-4d53-b315-2853a44adfa3 fwd="112.134.44.149" dyno= connect= service= status=503 bytes= protocol=https
> 2018-04-29T16:15:42.953185+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/" host=infinite-spire-46506.herokuapp.com request_id=0836432d-ba3d-420e-8dfd-e5397b61505f fwd="112.134.44.149" dyno= connect= service= status=503 bytes= protocol=https
> 2018-04-29T16:15:43.888978+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/favicon.ico" host=infinite-spire-46506.herokuapp.com request_id=0308334e-1a4f-46dc-be68-4821bdbc8492 fwd="112.134.44.149" dyno= connect= service= status=503 bytes= protocol=https
> 2018-04-29T16:16:20.824260+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/" host=infinite-spire-46506.herokuapp.com request_id=7e68acf5-9498-4d11-ac4e-d6338fc1bc24 fwd="112.134.44.149" dyno= connect= service= status=503 bytes= protocol=https
> 2018-04-29T16:16:22.301258+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/favicon.ico" host=infinite-spire-46506.herokuapp.com request_id=e738e823-5867-4d61-96a7-7ccc619964e4 fwd="112.134.44.149" dyno= connect= service= status=503 bytes= protocol=https

If anyone got a solution for this issue, please add it to this thread.

Thank you.

**Comment by hemanthcharlie** [comment]
https://devcenter.heroku.com/articles/getting-started-with-java#deploy-the-app

follow the steps given in this link

**Comment by charlie39** [comment]
Did it work ? lol

**Comment by anushil05** [comment]
No
