### ISSUE TITLE
Error: "FATAL: too many connections for role..."

### ISSUE THREAD

**Issue by akarki15** [heroku/java-getting-started#9]
Problem: 
Hobby-dev plan for postgres has connection limit of 20. Since showDatabase() in Main.java never closes the connection, the app reaches its connection cap in 20 refreshes. So, we get "FATAL: too many connections for role..." error after 20 refreshes. 

Solution: 
Close the connection after displaying the info from the database. Add connection.close() after writing the database content on the screen (i.e. after line 42).

**Comment by jonmountjoy** [comment]
Thank you.  I think it's closed properly now in my rewrite: https://github.com/heroku/java-getting-started/blob/master/src/main/java/Main.java#L52

**Comment by akarki15** [comment]
Cool!
